name: Test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [6.x, 7.x, 8.x, 10.x, 12.x]
        steps:
            -   uses: actions/checkout@v1
            -   name: setup node ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   run : npm install && npm run build
            -   run : npm run test
